apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sysdig-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.sysdig.com
    chart: shield
    targetRevision: "1.25.0"
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/zanghani/argocd-applications/main/sysdig-agent/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sysdig-agent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: result-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Santiagososs/example-voting-app
    targetRevision: main
    path: manifests/result
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Santiagososs/example-voting-app
    targetRevision: main
    path: manifests/vote
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Santiagososs/example-voting-app
    targetRevision: main
    path: manifests/worker
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
